{% set name = "hatch-nodejs-version" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 2428ea398dd053f019d2b7ac949dd6b690ca8e826b6d433ad13c5b6c475ae91b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - hatchling >=0.21.0

test:
  source_files:
    - tests
  imports:
    - hatch_nodejs_version  
  requires:
    - msys2-grep  # [win]
    - pip
    - pytest >=7.0.1
    - pytest-cov
  commands:
    - pip check
    - pip list
    - pip list | grep -iE 'hatch-nodejs-version\s*{{ version.replace('.', '\.') }}'
    - pytest -vvv --capture=tee-sys --cov=hatch_nodejs_version --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=80

about:
  home: https://github.com/agoose77/hatch-nodejs-version
  dev_url: https://github.com/agoose77/hatch-nodejs-version
  doc_url: https://github.com/agoose77/hatch-nodejs-version/blob/master/README.md
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Hatch plugin for versioning from a package.json file
  description: Hatch plugin to read pyproject.toml metadata from package.json

extra:
  recipe-maintainers:
    - bollwyvl
    - agoose77
    - thewchan
  skip-lints: python_build_tool_in_run
