{% set name = "hatch-nodejs-version" %}
{% set version = "0.3.1" %}
{% set sha256 = "0e55fd713d92c5c1ccfee778efecaa780fd8bcd276d4ca7aff9f6791f6f76d9c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_nodejs_version-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [py<37]

requirements:
  host:
    - hatchling
    - pip
    - python
    - wheel
  run:
    - hatchling >=0.21.0
    - python

test:
  source_files:
    - tests
  imports:
    - hatch_nodejs_version  
  requires:
    - m2-grep  # [win]
    - pip
    - pytest >=7.0.1
    - pytest-cov
  commands:
    - pip check
    - pip list
    - pip list | grep -iE 'hatch-nodejs-version\s*{{ version.replace('.', '\.') }}'
    - pytest -vvv --capture=tee-sys --cov=hatch_nodejs_version --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=80

about:
  home: https://github.com/agoose77/hatch-nodejs-version
  dev_url: https://github.com/agoose77/hatch-nodejs-version/
  doc_url: https://github.com/agoose77/hatch-nodejs-version/blob/master/README.md
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Hatch plugin for versioning from a package.json file
  description: Hatch plugin to read pyproject.toml metadata from package.json

extra:
  recipe-maintainers:
    - bollwyvl
    - agoose77
    - thewchan
