{% set name = "hatch-nodejs-version" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_nodejs_version-{{ version }}.tar.gz
  sha256: 0e55fd713d92c5c1ccfee778efecaa780fd8bcd276d4ca7aff9f6791f6f76d9c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - hatchling >=0.21.0
    - python >=3.7

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  imports:
    - hatch_nodejs_version
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests

about:
  home: https://github.com/agoose77/hatch-nodejs-version
  summary: Hatch plugin for versioning from a package.json file
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
    - agoose77
    - thewchan
